// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {oid} from '../models';

export function GetCurrentOids():Promise<Array<oid.Oid>>;

export function Greet(arg1:string):Promise<string>;

export function ParseMib():Promise<void>;
